name: elso

channels:
  - conda-forge

dependencies:
  - cmake>=3.20
  - gitpython==3.1.0
  - python==3.11
  - pybind11>=2.10.1
  - pytest>=7.1.2
  - pytest-regressions
  - boost==1.80
  - gcc==12.2.0
  - yfinance
  - quandl
