# Including elso library path for testing
import git, sys

repo = git.Repo(".", search_parent_directories=True)
PYTHON_PATH = repo.working_dir + "/src/python"
sys.path.append(str(PYTHON_PATH))

EXPECTED_STOCK_METADATA = [
    "52WeekChange",
    "SandP52WeekChange",
    "address1",
    "address2",
    "ask",
    "askSize",
    "auditRisk",
    "averageDailyVolume10Day",
    "averageVolume",
    "averageVolume10days",
    "beta",
    "bid",
    "bidSize",
    "boardRisk",
    "bookValue",
    "city",
    "companyOfficers",
    "compensationRisk",
    "country",
    "currency",
    "currentPrice",
    "currentRatio",
    "dayHigh",
    "dayLow",
    "debtToEquity",
    "dividendRate",
    "dividendYield",
    "earningsGrowth",
    "earningsQuarterlyGrowth",
    "ebitda",
    "ebitdaMargins",
    "enterpriseToEbitda",
    "enterpriseToRevenue",
    "enterpriseValue",
    "exDividendDate",
    "exchange",
    "fiftyDayAverage",
    "fiftyTwoWeekHigh",
    "fiftyTwoWeekLow",
    "financialCurrency",
    "firstTradeDateEpochUtc",
    "fiveYearAvgDividendYield",
    "floatShares",
    "forwardEps",
    "forwardPE",
    "freeCashflow",
    "fullTimeEmployees",
    "gmtOffSetMilliseconds",
    "governanceEpochDate",
    "grossMargins",
    "grossProfits",
    "heldPercentInsiders",
    "heldPercentInstitutions",
    "impliedSharesOutstanding",
    "industry",
    "lastDividendDate",
    "lastDividendValue",
    "lastFiscalYearEnd",
    "lastSplitDate",
    "lastSplitFactor",
    "longBusinessSummary",
    "longName",
    "marketCap",
    "maxAge",
    "messageBoardId",
    "mostRecentQuarter",
    "netIncomeToCommon",
    "nextFiscalYearEnd",
    "numberOfAnalystOpinions",
    "open",
    "operatingCashflow",
    "operatingMargins",
    "overallRisk",
    "pegRatio",
    "phone",
    "previousClose",
    "priceHint",
    "priceToBook",
    "priceToSalesTrailing12Months",
    "profitMargins",
    "quickRatio",
    "quoteType",
    "recommendationKey",
    "recommendationMean",
    "regularMarketDayHigh",
    "regularMarketDayLow",
    "regularMarketOpen",
    "regularMarketPreviousClose",
    "regularMarketVolume",
    "returnOnAssets",
    "returnOnEquity",
    "revenueGrowth",
    "revenuePerShare",
    "sector",
    "shareHolderRightsRisk",
    "sharesOutstanding",
    "shortName",
    "symbol",
    "targetHighPrice",
    "targetLowPrice",
    "targetMeanPrice",
    "targetMedianPrice",
    "timeZoneFullName",
    "timeZoneShortName",
    "totalCash",
    "totalCashPerShare",
    "totalDebt",
    "totalRevenue",
    "trailingAnnualDividendRate",
    "trailingAnnualDividendYield",
    "trailingEps",
    "trailingPE",
    "trailingPegRatio",
    "twoHundredDayAverage",
    "underlyingSymbol",
    "uuid",
    "volume",
    "website",
    "zip",
]

EXPECTED_DATASET_CODES = {
    "SELIC-daily": "BCB/11",
    "SELIC-monthly": "BCB/4390",
    "SELIC-annually": "BCB/432",
    "IPCA": "BCB/433",
    "IGPM": "BCB/189",
    "CDI-daily": "BCB/12",
    "CDI-monthly": "BCB/4391",
    "CDI-annually": "BCB/4391",
}
