name: build

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen and GraphViz
      run: sudo apt-get install doxygen graphviz -y
    
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile

    - name: Create .nojekyll
      run: touch html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
